/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ator.UI;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author carla
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        inserirIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFundoAtor = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuAplicativoAtor = new javax.swing.JMenu();
        itmSairAtor = new javax.swing.JMenuItem();
        mnuCadastrosAtor = new javax.swing.JMenu();
        itmCadClientesAtor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Projeto Ator");
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);

        lblFundoAtor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ator/UI/ator.png"))); // NOI18N

        mnuAplicativoAtor.setMnemonic('f');
        mnuAplicativoAtor.setText("Aplicativo Ator");

        itmSairAtor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSairAtor.setMnemonic('x');
        itmSairAtor.setText("Sair");
        itmSairAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairAtorActionPerformed(evt);
            }
        });
        mnuAplicativoAtor.add(itmSairAtor);

        menuBar.add(mnuAplicativoAtor);

        mnuCadastrosAtor.setText("Cadastros");
        mnuCadastrosAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrosAtorActionPerformed(evt);
            }
        });

        itmCadClientesAtor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadClientesAtor.setText("Clientes");
        itmCadClientesAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadClientesAtorActionPerformed(evt);
            }
        });
        mnuCadastrosAtor.add(itmCadClientesAtor);

        menuBar.add(mnuCadastrosAtor);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFundoAtor, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFundoAtor)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inserirIcone() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconAtor.png")));
    }
    
    private void itmSairAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairAtorActionPerformed
       if (JOptionPane.showConfirmDialog(null, "Deseja Sair do Sistema?", "Aplicativo Ator", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

    }//GEN-LAST:event_itmSairAtorActionPerformed

    private void itmCadClientesAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadClientesAtorActionPerformed
        //Verfica se o formulário é nulo e está visivel
        if ((frmClientes == null) || (!frmClientes.isVisible()))
        {
            frmClientes = new frmClientes();
            frmClientes.setVisible(true);
        }
    }//GEN-LAST:event_itmCadClientesAtorActionPerformed

    private void mnuCadastrosAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrosAtorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastrosAtorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem itmCadClientesAtor;
    javax.swing.JMenuItem itmSairAtor;
    javax.swing.JLabel lblFundoAtor;
    javax.swing.JMenuBar menuBar;
    javax.swing.JMenu mnuAplicativoAtor;
    javax.swing.JMenu mnuCadastrosAtor;
    // End of variables declaration//GEN-END:variables

    //Declarando o objeto formClientes
    private frmClientes frmClientes;


}
